name: Python application

on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@
      with:
          python-version: "3.10"
      
    - name: Install dependencies
      working-directory: source_code/pipelines
      shell: bash
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
    - name: Lint with pylint
      working-directory: source_code/pipelines
      shell: bash
      run: pylint cli/

    - name: Check with mypy
      working-directory: source_code/pipelines
      shell: bash
      run: mypy cli/
    
    - name: Test with pytest
      working-directory: source_code/pipelines
      shell: bash
      run: pytest